### ISSUE TITLE
Users should be able to create a new account

### ISSUE THREAD

**Issue by thechinedu** [thechinedu/picstagram#1]
Integrate with the firebase API to enable creation of user accounts from the sign up page. 

### Tasks

- [x] Create sign up page containing the required fields 
- [x] Users should be able to sign up with their email address
- [x] When a user submits their details, they should receive a verification email
- [x] Add integration and E2E tests
