### ISSUE TITLE
Users should be able to upload images to their feed

### ISSUE THREAD

**Issue by thechinedu** [thechinedu/picstagram#10]
When a user clicks the `plus` icon in the header, they should see a dialog box for creating a new post with a similar workflow like on instagram.

### Tasks

- [ ] Set up cloudinary for image/video hosting
- [ ] Add generic dialog component
- [ ] Implement functionality to enable uploading images 
- [ ] Show uploaded posts on user feed
