### ISSUE TITLE
Users should be able to log in to the application

### ISSUE THREAD

**Issue by thechinedu** [thechinedu/picstagram#2]
Integrate with the firebase API to enable users sign in to their account.

### Tasks

- [x] Create login page containing the required fields 
- [x] Users should be able to log in to the application
- [x] Add integration and E2E tests
