### ISSUE TITLE
Users should see a dashboard after login

### ISSUE THREAD

**Issue by thechinedu** [thechinedu/picstagram#3]
Once a user logs in to the application, they should be greeted to their feed which would contain posts from their accounts and accounts that they follow.

### Tasks

- [x] Add component to display empty feed when a user hasn't yet followed any account
- [x] Add component for showing stories (just the card section and no functionality for showing the stories themselves as of yet)
- [x] Add component for showing videos and images
